version: "3.7"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sFox0Y8HPVpFe4nZDh4Z
      MYSQL_DATABASE: mobile
    ports:
      - "3306:3306"
    volumes:
      - mydb_data:/var/lib/mysql
volumes:
  mydb_data:
